Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Arrancando MAQUINAS"
  config_wordpress="/srv/www/wordpress/wp-config.php"
  config_mysql="/"
  ipmysql="192.168.33.10"
  pass_mysql="passtest"
  config.vm.boot_timeout= 6000


  

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.box_version = "20230607.0.5"
    db.vm.network "private_network", ip: "#{ipmysql}"
    db.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install mysql-server -y

      echo "EJECUTANDO SCRIPTS DE MYSQL"
      mysql -h localhost -u root -p -e "DROP DATABASE wordpress;" 2>/dev/null
      mysql -h localhost -u root -p -e "DROP USER wordpress;" 2>/dev/null
      cat /vagrant/MYSQL/init.sql
      sudo mysql -u root < /vagrant/MYSQL/init.sql

      sudo service mysql start

      sudo sed -i 's/^bind-address\s*=.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf

      sudo systemctl restart mysql

    SHELL

    db.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.name = "bbdd-wordpress"
    end
  end



  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.box_version = "20230607.0.5"
    web.vm.network "private_network", ip: "192.168.33.11"
    web.vm.provision "shell", inline: <<-SHELL

      echo "--------------ENTRANDO EN SHELL DE WEB-------------"
      sudo apt update
      sudo apt install apache2 \
                ghostscript \
                libapache2-mod-php \
                php \
                php-bcmath \
                php-curl \
                php-imagick \
                php-intl \
                php-json \
                php-mbstring \
                php-mysql \
                php-xml \
                php-zip -y
      echo ###############################
      echo #####INSTALACIÓN WORDPRESS#####
      echo ###############################
      echo "Instalando WORDPRESS" 
      sudo mkdir -p /srv/www
      sudo chown www-data: /srv/www
      curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
      cp /vagrant/WORDPRESS/wordpress.conf /etc/apache2/sites-available/
      sudo a2ensite wordpress
      sudo a2enmod rewrite
      sudo a2dissite 000-default
      sudo service apache2 reload

      echo '#################################'
      echo '#####CONFIGURACIÓN WORDPRESS#####'
      echo '#################################'   
      echo "CONFIGURANDO WORDPRESS..."

      sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php #{config_wordpress}

      sudo -u www-data sed -i 's/database_name_here/wordpress/' #{config_wordpress}
      sudo -u www-data sed -i 's/username_here/wordpress/' #{config_wordpress}
      sudo -u www-data sed -i 's/password_here/#{pass_mysql}/' #{config_wordpress}

      sh /vagrant/WORDPRESS/keys.sh

      cat #{config_wordpress}
    SHELL

    web.vm.provider "virtualbox" do |vb|

      vb.memory = "4096"
      vb.name = "web-wordpress"
    end
  end



end
