# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  ######################
  ###### VARIABLES######
  ######################
  config_wordpress="/srv/www/wordpress/wp-config.php"

  pass_mysql="passtest"




  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.


  #config.vm.name = "wordpress-test"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
   vb.memory = "4096"
   vb.name = "wordpress-test"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    echo "--------------ENTRANDO EN SHELL-------------"
    sudo apt update
    sudo apt install apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip -y
    echo ###############################
    echo #####INSTALACIÓN WORDPRESS#####
    echo ###############################
    echo "Instalando WORDPRESS" 

    sudo mkdir -p /srv/www
    sudo chown www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
    cp /vagrant/WORDPRESS/wordpress.conf /etc/apache2/sites-available/
    sudo a2ensite wordpress
    sudo a2enmod rewrite
    sudo a2dissite 000-default
    sudo service apache2 reload

    ###############################
    #####CONFIGURACION MYSQL#######
    ###############################

    echo "EJECUTANDO SCRIPTS DE MYSQL"
    cat /vagrant/MYSQL/init.sql
    sudo mysql -u root < /vagrant/MYSQL/init.sql
    sudo service mysql start

    echo '#################################'
    echo '#####CONFIGURACIÓN WORDPRESS#####'
    echo '#################################'   
    echo "CONFIGURANDO WORDPRESS..."

    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php #{config_wordpress}
    sudo -u www-data sed -i 's/database_name_here/wordpress/' #{config_wordpress}
    sudo -u www-data sed -i 's/username_here/wordpress/' #{config_wordpress}
    sudo -u www-data sed -i 's/password_here/#{pass_mysql}/' #{config_wordpress}
    ###############################################

    sh /vagrant/WORDPRESS/keys.sh

    echo "###########################################"
    ip a
    echo "###########################################"
    cat #{config_wordpress}

  SHELL
end
